matrix:
  include:
  - dist: xenial
    language: minimal
    os: linux
    services:
    - docker
  - os: osx
    language: minimal
script:
- ./script/download-mmdb.sh
- ./script/build-travis-${TRAVIS_OS_NAME}.sh
